// Browser-safe exports — no Node.js dependencies (no better-sqlite3, pino, etc.)

export {
  TASK_STATUSES,
  type TaskStatus,
  type TaskIntent,
  AUTO_REVIEW_STRATEGIES,
  type AutoReviewStrategy,
  AUTO_REVIEW_FINDING_SOURCES,
  type AutoReviewFindingSource,
  AUTO_REVIEW_PREVIOUS_FINDING_STATUSES,
  type AutoReviewPreviousFindingStatus,
  type AutoReviewFindingSeverity,
  AUTO_REVIEW_SECURITY_COVERAGE_AREAS,
  type AutoReviewSecurityCoverageArea,
  type AutoReviewSecurityCoverageStatus,
  type AutoReviewSecurityCoverage,
  type AutoReviewBlockerHistoryEntry,
  type AutoReviewFinding,
  type AutoReviewReworkSnapshot,
  type AutoReviewState,
  type Project,
  type CreateProjectInput,
  type AppSettings,
  type UpdateAppSettingsInput,
  type Task,
  type TaskEffectiveRuntime,
  type TaskQaMandatoryCheck,
  type TaskQaCommandEvidence,
  type TaskQaCommandStatus,
  type TaskQaSkippedCheck,
  type TaskQaSourceFingerprint,
  type TaskAcceptancePack,
  type TaskAcceptancePackReadiness,
  type TaskArtifactTrustBatchCounts,
  type TaskArtifactTrustClaimOutcome,
  type TaskArtifactTrustLevel,
  type TaskArtifactTrustNextAction,
  type TaskArtifactTrustRollup,
  type WorkflowTimeline,
  type WorkflowTimelineArtifact,
  type WorkflowTimelineArtifactState,
  type WorkflowTimelineAttempt,
  type WorkflowTimelineClaim,
  type WorkflowTimelineClaimOutcome,
  type WorkflowTimelineContext,
  type WorkflowTimelineEvent,
  type WorkflowTimelineEventKind,
  type WorkflowTimelineEvidence,
  type WorkflowTimelineEvidenceLink,
  type WorkflowTimelineEvidenceLinkRelation,
  WORKFLOW_TIMELINE_GENERIC_ARTIFACT_KINDS,
  type WorkflowTimelineGenericArtifactKind,
  type WorkflowTimelineSourceKind,
  type WorkflowTimelineTrustLevel,
  type TaskStageArtifactState,
  type TaskRequirementsSnapshot,
  type TaskRequirementsSnapshotResponse,
  type TaskStageArtifact,
  type TaskStageArtifactAttempt,
  type TaskRequirementsPromptContext,
  type TaskOperatorEvidenceResponse,
  type CreateTaskInput,
  type UpdateTaskInput,
  type TaskComment,
  type TaskCommentAttachment,
  type CreateTaskCommentInput,
  TASK_EVENTS,
  type TaskEvent,
  type TaskEventInput,
  type ReorderTaskInput,
  MEMORY_ITEM_STATUSES,
  type MemoryItemStatus,
  MEMORY_SCOPES,
  type MemoryScope,
  MEMORY_REDACTION_STATUSES,
  type MemoryRedactionStatus,
  MEMORY_SOURCE_KINDS,
  type MemorySourceKind,
  MEMORY_ITEM_TYPES,
  type MemoryItemType,
  MEMORY_FAILURE_FAMILIES,
  type MemoryFailureFamily,
  MEMORY_CLAIM_SOURCE_KINDS,
  MEMORY_CLAIM_STATUSES,
  type MemoryClaimSourceKind,
  type MemoryClaimStatus,
  type MemoryClaimSource,
  type MemoryClaim,
  MEMORY_WORKFLOW_KINDS,
  type MemoryWorkflowKind,
  MEMORY_LIFECYCLE_ACTIONS,
  type MemoryLifecycleAction,
  type MemoryItem,
  type CreateMemoryItemInput,
  type UpdateMemoryItemInput,
  type MemoryUsageEvent,
  type MemoryLifecycleEvent,
  type TaskMemoryCandidatesResponse,
  type ProjectKnowledgeCounts,
  type ProjectKnowledgeResponse,
  type MemoryItemBroadcastPayload,
  type TaskRuntimeUsageEvent,
  type RuntimeUsageTotals,
  type TaskRuntimeUsageResponse,
  type ProjectRuntimeUsageResponse,
  type ProjectQueueBacklogItem,
  type ProjectQueueStateResponse,
  TASK_SPLIT_PROPOSAL_STATUSES,
  type TaskSplitProposalStatus,
  type TaskSplitProposalSourceKind,
  type TaskSplitProposedChild,
  type TaskSplitProposal,
  type TaskSplitProposalResponse,
  type TaskWorktreeInspection,
  type TaskWorktreeCleanupResult,
  type WsEventType,
  type WsEvent,
  type RoadmapCompletePayload,
  type RoadmapSplitRequiredPayload,
  type RoadmapErrorPayload,
  type TaskCommitPayload,
  type RuntimeLimitBroadcastPayload,
  type TaskOperatorWsPayload,
  type TaskManualHandoffWsPayload,
  type ProjectMemoryCandidateWsPayload,
  type ProjectUsageWsPayload,
  type ProjectQueueWsPayload,
  type ProjectWorktreeWarningWsPayload,
  type ChatMessage,
  type ChatMessageAttachment,
  type ChatAttachment,
  type ChatRequest,
  type ChatStreamTokenPayload,
  type ChatDonePayload,
  type ChatErrorPayload,
  type ChatAction,
  type ChatActionCreateTask,
  type ChatActionCreateFollowUp,
  type ChatActionStartExplore,
  type ChatActionExplainBlocker,
  type ChatActionPrepareReplan,
  isRuntimeTransport,
  RUNTIME_TRANSPORTS,
  RuntimeTransport,
  type RuntimeDescriptor,
  type RuntimeProfileUsage,
  type RuntimeProfile,
  type CreateRuntimeProfileInput,
  type UpdateRuntimeProfileInput,
  type EffectiveRuntimeProfileSource,
  type EffectiveRuntimeProfileSelection,
  RuntimeLimitSource,
  RuntimeLimitStatus,
  RuntimeLimitPrecision,
  RuntimeLimitScope,
  type RuntimeLimitWindow,
  type RuntimeLimitSnapshot,
  type RuntimeLimitEventPayload,
  USAGE_EVENT_OUTCOMES,
  type UsageEventOutcome,
  type WarmupBroadcastPayload,
  type TaskQuestionWsPayload,
  type ChatSessionSource,
  type ChatSession,
  type CreateChatSessionInput,
  type UpdateChatSessionInput,
  type ChatSessionMessage,
} from "./types.js";

export {
  AIF_RAISE_QUESTIONS_ACTION,
  AIF_RAISE_QUESTIONS_FENCE_LANGUAGE,
  REQUIREMENT_ANSWER_TYPES,
  REQUIREMENT_QUESTION_STAGES,
  REQUIREMENT_QUESTION_STATUSES,
  asksForRawSecret,
  containsSecretLikeAnswer,
  normalizeAifRaiseQuestionsContract,
  parseAifRaiseQuestionsContract,
  validateRequirementAnswer,
  type AifRaiseQuestionsAction,
  type AifRaiseQuestionsContract,
  type RequirementAnswerType,
  type RequirementAnswerValidationResult,
  type RequirementQuestionAnswerAuthor,
  type RequirementQuestionStage,
  type RequirementQuestionStatus,
  type TaskRequirementQuestion,
  type TaskRequirementQuestionAnswerInput,
  type TaskRequirementQuestionBatch,
  type TaskRequirementQuestionBatchAnswerInput,
  type TaskRequirementQuestionInput,
  type TaskRequirementQuestionsResponse,
} from "./requirementsQuestions.js";
export {
  REQUIREMENTS_LIFECYCLE_EVENTS,
  REQUIREMENTS_LIFECYCLE_METRIC_KEY,
  buildRequirementsLifecycleMetric,
  type RequirementsLifecycleDimensions,
  type RequirementsLifecycleDimensionValue,
  type RequirementsLifecycleEventName,
  type RequirementsLifecycleMetric,
} from "./requirementsObservability.js";

export {
  TASK_INTENTS,
  TASK_INTENT_CONTRACTS,
  formatTaskIntentOptionsForPrompt,
  formatTaskIntentPrimaryConstraints,
  formatTaskIntentContractForPrompt,
  getTaskIntentContract,
  getTaskIntentPolicy,
  inferTaskIntent,
  isTaskIntent,
  normalizeTaskIntent,
  resolveTaskIntentDefaults,
  validateTaskIntentChangedFiles,
  validateGeneratedTaskIntent,
  type InferTaskIntentInput,
  type ResolvedTaskIntentDefaults,
  type TaskIntentContract,
  type TaskIntentDefaults,
  type TaskIntentChangedFilesIssue,
  type TaskIntentPolicy,
  type TaskIntentUseSubagentsDefault,
  type ValidateTaskIntentChangedFilesInput,
  type ValidateTaskIntentChangedFilesResult,
  type ValidateGeneratedTaskIntentInput,
  type ValidateGeneratedTaskIntentResult,
} from "./taskIntent.js";
export {
  PERMISSION_EXECUTION_POLICIES,
  PERMISSION_MODES,
  PERMISSION_POLICY_INTENTS,
  classifyDangerousShellCommand,
  decideHumanApproval,
  decidePolicyBypass,
  decideShellPermission,
  getPermissionExecutionPolicy,
  isPathAllowedByPermissionPolicy,
  isPermissionMode,
  isPermissionModeAllowedForIntent,
  isPermissionPolicyIntent,
  redactPermissionPolicyValue,
  type ApprovalDecision,
  type ApprovalDecisionInput,
  type BypassDecision,
  type BypassDecisionInput,
  type DangerousShellCategory,
  type DangerousShellCommandClassification,
  type PermissionAuditMetadata,
  type PermissionBypassVisibilityPolicy,
  type PermissionDecisionOutcome,
  type PermissionExecutionPolicy,
  type PermissionFileBoundaryMode,
  type PermissionFileBoundaryPolicy,
  type PermissionMode,
  type PermissionNetworkPolicy,
  type PermissionPolicyIntent,
  type PermissionShellPolicy,
  type RedactedPermissionPolicyValue,
  type ShellPermissionDecision,
  type ShellPermissionDecisionInput,
} from "./permissionPolicy.js";
export {
  WORKFLOW_PACKS,
  getWorkflowPack,
  validateGeneratedWorkflowTask,
  type WorkflowPack,
} from "./workflowPacks.js";

export {
  STATUS_CONFIG,
  ORDERED_STATUSES,
  WARMUP_TARGETS,
  WARMUP_WORKFLOW_KINDS,
  DEFAULT_WARMUP_TARGET,
  RUNTIME_PROFILE_MODES,
  RUNTIME_STAGES,
  RUNTIME_STAGE_PROFILE_MODE,
  isWarmupWorkflowKind,
  isRuntimeProfileMode,
  isRuntimeStage,
  normalizeRuntimeStage,
  runtimeProfileModeForStage,
  type WarmupTarget,
  type WarmupWorkflowKind,
  type WarmupProfileMode,
  type RuntimeProfileMode,
  type RuntimeStage,
  type RuntimeStageOrProfileMode,
} from "./constants.js";
export { HUMAN_ACTIONS_BY_STATUS } from "./stateMachine.js";
export { withTimeout } from "./withTimeout.js";
export {
  AUDIT_CARD_FINAL_STATUSES,
  AUDIT_CARD_VERIFICATION_STRENGTHS,
  buildAuditCardDecisionFromReport,
  classifyAuditCardDecision,
  extractWeakOrDiscardedAuditFindings,
  type AuditCardDecision,
  type AuditCardDecisionInput,
  type AuditCardFinalStatus,
  type AuditCardVerificationStrength,
  type BuildAuditCardDecisionFromReportInput,
  type WeakOrDiscardedAuditFinding,
} from "./auditCardDecision.js";
export {
  buildRuntimeLimitSignature,
  normalizeRuntimeLimitSnapshot,
  redactProviderText,
  redactProviderTextForLogs,
  resolveRuntimeLimitFutureHint,
  sanitizeRuntimeLimitSnapshotForExposure,
  sanitizeProviderMeta,
  selectViolatedWindowForExactThreshold,
  type RuntimeLimitFutureHint,
  type RuntimeLimitFutureHintSource,
  type RuntimeLimitSnapshotExposure,
  type SafeRuntimeErrorCategory,
  type SafeRuntimeErrorReason,
} from "./runtimeLimitUtils.js";

// Plan path utilities (pure functions, browser-safe — separate module with no Node.js deps)
export { slugify, generatePlanPath } from "./planPath.js";
export type { GeneratePlanPathOptions } from "./planPath.js";

// Sync types (browser-safe subset — types only, no Node.js logger dependency)
export type { SyncDirection, ConflictResolution, SyncEvent, PlanAnnotation } from "./sync.js";

// Planner mode defaults (pure, browser-safe)
export { defaultsForMode } from "./plannerDefaults.js";
export type { PlannerMode, PlannerFlagDefaults } from "./plannerDefaults.js";
